[project]
name = "graph_weather"
version = "1.0.89"
description = "Graph-based AI Weather models"
authors = ["Jacob Prince-Bieker <jacob@bieker.tech>"]
channels = ["pyg", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64", "osx-arm64"]

[feature.cuda.system-requirements]
cuda = "12"

[feature.cuda.target.linux-64.dependencies]
cuda-version = "12.*"
pytorch-gpu = ">=2.4"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.4"

[pypi-dependencies]
graph_weather_editable = { path = ".", editable = true }
torch-harmonics = "*"

[dependencies]
python = "3.12.*"
pip = "*"
pytest = "*"
pre-commit = "*"
ruff = "*"
torchvision = "*"
xarray = "*"
pandas = "*"
h3-py = "3.*"
numcodecs = "*"
scipy = "*"
zarr = ">=3.0.0"
pyg = "*"
pytorch-cluster = "*"
pytorch-scatter = "*"
pytorch-spline-conv = "*"
pytorch-sparse = "*"
tqdm = "*"
lightning = "*"
einops = "*"
fsspec = "*"
datasets = "*"
trimesh = "*"
pysolar = "*"
rtree = "*"


[environments]
cpu = ["cpu"]
cuda = ["cuda"]
