[project]
name = "graph_weather"
version = "1.0.88"
description = "Graph-based AI Weather models"
authors = ["Jacob Prince-Bieker <jacob@bieker.tech>"]
channels = ["pyg", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64", "osx-arm64"]

[feature.gpu.system-requirements]
cuda = "12.*"

[feature.gpu.dependencies]
cuda-version = "12.*"
pytorch-gpu = ">=2.5"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.5"

[environments]
cpu = ["cpu"]
default = ["gpu"]

[tasks]
tinstall = "python -m pip install torch-geometric-temporal"

[dependencies]
python = "3.12.*"
torchvision = "*"
pytorch-cluster = "*"
pytorch-scatter = "*"
xarray = "*"
pytorch-spline-conv = "*"
pandas = "*"
h3-py = "*"
numcodecs = "*"
scipy = "*"
zarr = ">=3.0.0"
pyg = "*"
tqdm = "*"
pytorch-sparse = "*"
lightning = "*"
einops = "*"
fsspec = "*"
datasets = "*"
pip = "*"
pytest = "*"
pre-commit = "*"
ruff = "*"


[pypi-dependencies]
pysolar = "*"
graph_weather = { path = ".", editable = true }
